services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    platform: linux/amd64
    container_name: gitlab-ce
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8080:80'
      - '8443:443'
      - '2242:22'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
    networks:
      - compose
    shm_size: '2gb'

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

networks:
  compose:
    external: true
