services:
  aerospikedb:
    container_name: aerospikedb
    hostname: aerospikedb
    image: aerospike/aerospike-server:latest
    # environment:
    #   NAMESPACE: test
    networks:
      - compose
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    volumes:
      - aerospike-data:/opt/aerospike/data
  
networks:
  compose:
    external: true

volumes:
  aerospike-data:
