services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone
    platform: linux/amd64
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - nacos-data:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - compose
  # prometheus:
  #   container_name: prometheus
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - nacos
  #   restart: on-failure
  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana:latest
  #   ports:
  #     - 3000:3000
  #   restart: on-failure

networks:
  compose:
    external: true

volumes:
  nacos-data:
  