---
volumes:
  prometheus_data: {}
  grafana_data: {}
  promtail_data: {}

services:

  alertmanager:
    container_name: alertmanager
    hostname: alertmanager
    image: prom/alertmanager
    volumes:
      - ./alertmanager.conf:/etc/alertmanager/alertmanager.conf
    command:
      - '--config.file=/etc/alertmanager/alertmanager.conf'
    ports:
      - 9093:9093
    networks:
      - compose

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./alert_rules.yaml:/etc/prometheus/alert_rules.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    links:
      - alertmanager:alertmanager
    ports:
      - 9090:9090
    networks:
      - compose

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana-oss
    volumes:
      - ./grafana_datasources.yaml:/etc/grafana/provisioning/datasources/all.yaml
      - ./grafana_config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - compose
  
  loki:
    container_name: loki
    hostname: loki
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - compose

  promtail:
    container_name: promtail
    hostname: promtail
    image: grafana/promtail:2.8.0
    volumes:
      - promtail_data:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - compose

networks:
  compose:
    external: true
