global:
  # How frequently to scrape targets by default.
  # [ scrape_interval: <duration> | default = 1m ]
  scrape_interval: 15s
  # How long until a scrape request times out.
  # [ scrape_timeout: <duration> | default = 10s ]

  # How frequently to evaluate rules. default = 1m
  # [ evaluation_interval: <duration> | default = 1m ]
  evaluation_interval: 15s

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #   [ <labelname>: <labelvalue> ... ]

  # File to which PromQL queries are logged.
  # Reloading the configuration will reopen the file.
  # [ query_log_file: <string> ]

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
# rule_files:
#   [ - <filepath_glob> ... ]
rule_files:
  - /etc/prometheus/alert_rules.yaml

# A list of scrape configurations.
# scrape_configs:
#   [ - <scrape_config> ... ]
scrape_configs:
  - job_name: 'vad-metrics'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['docker.for.mac.host.internal:9091']

# Alerting specifies settings related to the Alertmanager.
# alerting:
#   alert_relabel_configs:
#     [ - <relabel_config> ... ]
#   alertmanagers:
#     [ - <alertmanager_config> ... ]
alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alertmanager:9093"]

# Settings related to the remote write feature.
# remote_write:
#   [ - <remote_write> ... ]

# Settings related to the remote read feature.
# remote_read:
#   [ - <remote_read> ... ]

# Storage related settings that are runtime reloadable.
# storage:
#   [ tsdb: <tsdb> ]
#   [ exemplars: <exemplars> ]

# Configures exporting traces.
# tracing:
#   [ <tracing_config> ]
